Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,11 +50,12 @@ jobs:
         run: exit 1  
         
   dev-tms:
-    needs: [Schedule_Validation]
-    if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
+    needs: [Schedule_Validation, dev-btms, dev-btms-history]
+    if: ${{ needs.Schedule_Validation.outputs.status == 'true' || always() }}
+    #if: ${{ needs.Schedule_Validation.outputs.status }}== 'true' 
     runs-on: ubuntu-latest
-    needs: [dev-btms, dev-btms-history]
-    if: always() # always run even if a previous step fails
+    #needs: [dev-btms, dev-btms-history]
+    #if: always() # always run even if a previous step fails
     steps:
       - name: Delay for 30 sec
         run: sleep 10 # 900 seconds = 15 minutes
@@ -63,46 +64,46 @@ jobs:
       #- name: Intentionally fail Job 3
         #run: exit 1    
         
-  dev-imaging:
-    needs: [Schedule_Validation]
-    if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
-    runs-on: ubuntu-latest
-    needs: [dev-btms, dev-btms-history]
-    if: always() # always run even if a previous step fails
-    steps:
-      - name: Delay for 30 sec
-        run: sleep 10 # 900 seconds = 15 minutes
-      - name: Job4 Testing
-        run: echo "Job4 Third" 
-      - name: Intentionally fail Job 4
-        run: exit 1    
+  # dev-imaging:
+  #   needs: [Schedule_Validation]
+  #   if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
+  #   runs-on: ubuntu-latest
+  #   needs: [dev-btms, dev-btms-history]
+  #   if: always() # always run even if a previous step fails
+  #   steps:
+  #     - name: Delay for 30 sec
+  #       run: sleep 10 # 900 seconds = 15 minutes
+  #     - name: Job4 Testing
+  #       run: echo "Job4 Third" 
+  #     - name: Intentionally fail Job 4
+  #       run: exit 1    
         
         
-  qc-btms:
-    needs: [Schedule_Validation]
-    if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
-    runs-on: ubuntu-latest
-    needs: [dev-tms, dev-imaging]
-    if: always() # always run even if a previous step fails
-    steps:
-      - name: Delay for 30 sec
-        run: sleep 10 # 900 seconds = 15 minutes
-      - name: Job5 Testing
-        run: echo "Job5 Third"
-      - name: Intentionally fail Job 4
-        run: exit 1  
+  # qc-btms:
+  #   needs: [Schedule_Validation]
+  #   if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
+  #   runs-on: ubuntu-latest
+  #   needs: [dev-tms, dev-imaging]
+  #   if: always() # always run even if a previous step fails
+  #   steps:
+  #     - name: Delay for 30 sec
+  #       run: sleep 10 # 900 seconds = 15 minutes
+  #     - name: Job5 Testing
+  #       run: echo "Job5 Third"
+  #     - name: Intentionally fail Job 4
+  #       run: exit 1  
         
         
-  qb-btms-history:
-    needs: [Schedule_Validation]
-    if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
-    runs-on: ubuntu-latest
-    needs: [dev-tms, dev-imaging]
-    if: always() # always run even if a previous step fails
-    steps:
-      - name: Delay for 30 sec
-        run: sleep 10 # 900 seconds = 15 minutes
-      - name: Job6 Testing
+  # qb-btms-history:
+  #   needs: [Schedule_Validation]
+  #   if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
+  #   runs-on: ubuntu-latest
+  #   needs: [dev-tms, dev-imaging]
+  #   if: always() # always run even if a previous step fails
+  #   steps:
+  #     - name: Delay for 30 sec
+  #       run: sleep 10 # 900 seconds = 15 minutes
+  #     - name: Job6 Testing
         run: echo "Job6 Third"
       #- name: Intentionally fail Job 4
         #run: exit 1  
