Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,6 +32,8 @@ jobs:
         run: sleep 30 # 900 seconds = 15 minutes
       - name: Job3 Testing
         run: echo "Job3 Third"
+      - name: Intentionally fail Job 3
+        run: exit 1    
         
   Job4:
     runs-on: ubuntu-latest
@@ -42,3 +44,27 @@ jobs:
         run: sleep 30 # 900 seconds = 15 minutes
       - name: Job4 Testing
         run: echo "Job4 Third" 
+      - name: Intentionally fail Job 4
+        run: exit 1    
+        
+        
+  Job5:
+    runs-on: ubuntu-latest
+    needs: [Job3, Job4]
+    if: always() # always run even if a previous step fails
+    steps:
+      - name: Delay for 30 sec
+        run: sleep 30 # 900 seconds = 15 minutes
+      - name: Job3 Testing
+        run: echo "Job3 Third"
+        
+        
+  Job6:
+    runs-on: ubuntu-latest
+    needs: [Job3, Job4]
+    if: always() # always run even if a previous step fails
+    steps:
+      - name: Delay for 30 sec
+        run: sleep 30 # 900 seconds = 15 minutes
+      - name: Job4 Testing
+        run: echo "Job4 Third"      
