Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,10 +44,10 @@ jobs:
     if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
     runs-on: ubuntu-latest
     steps:
-      #- name: Job2 Testing
-        #run: echo "Job2 Second"
-      - name: Intentionally fail Job 2
-        run: exit 1  
+      - name: Job2 Testing
+        run: echo "Job2 Second"
+      # - name: Intentionally fail Job 2
+      #   run: exit 1  
         
   dev-tms:
     needs: [Schedule_Validation, dev-btms, dev-btms-history]
