Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,16 +53,16 @@ jobs:
     outputs:
       job_status: ${{ job.status }}
 
-  dev-tms:
-    needs: [dev-btms, dev-btms-history, Schedule_Validation] 
-    if: ${{ needs.Schedule_Validation.outputs.status}}== 'true'
-    # if: ${{ needs.Schedule_Validation.outputs.status}} == 'true'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Delay for 30 sec
-        run: sleep 10
-      - name: Job3 Testing
-        run: echo "Job3 Third"
+  # dev-tms:
+  #   needs: [dev-btms, dev-btms-history, Schedule_Validation] 
+  #   if: ${{ needs.Schedule_Validation.outputs.status}}== 'true'
+  #   # if: ${{ needs.Schedule_Validation.outputs.status}} == 'true'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Delay for 30 sec
+  #       run: sleep 10
+  #     - name: Job3 Testing
+  #       run: echo "Job3 Third"
 
         
   # dev-tms:
@@ -77,19 +77,19 @@ jobs:
       #- name: Intentionally fail Job 3
         #run: exit 1    
         
-  # dev-imaging:
-  #   needs: [Schedule_Validation, dev-btms, dev-btms-history]
-  #   if: ${{ needs.Schedule_Validation.outputs.status }}== 'true' && always ()
-  #   runs-on: ubuntu-latest
-  #   # needs: [dev-btms, dev-btms-history]
-  #   # if: always() # always run even if a previous step fails
-  #   steps:
-  #     - name: Delay for 30 sec
-  #       run: sleep 10 # 900 seconds = 15 minutes
-  #     - name: Job4 Testing
-  #       run: echo "Job4 Third" 
-  #     - name: Intentionally fail Job 4
-  #       run: exit 1    
+  dev-imaging:
+    # needs: [Schedule_Validation, dev-btms, dev-btms-history]
+    # if: ${{ needs.Schedule_Validation.outputs.status }}== 'true' && always ()
+    runs-on: ubuntu-latest
+    needs: [dev-btms, dev-btms-history]
+    if: always() # always run even if a previous step fails
+    steps:
+      - name: Delay for 30 sec
+        run: sleep 10 # 900 seconds = 15 minutes
+      - name: Job4 Testing
+        run: echo "Job4 Third" 
+      - name: Intentionally fail Job 4
+        run: exit 1    
         
         
   # qc-btms:
