Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,7 +13,7 @@ jobs:
     steps:
       - name: cron
         run: |
-            if [[ "$(date '+%m-%d')" == "08-10" ]]; then
+            if [[ "$(date '+%m-%d')" == "08-15" ]]; then
                 echo "Triggering the Scheduled Pipeline"
             else
               echo "Skipping the Pipeline as it is not scheduled to run in this specified date"
@@ -76,20 +76,20 @@ jobs:
       #- name: Intentionally fail Job 3
         #run: exit 1    
         
-  dev-imaging:
-    needs: [dev-btms, dev-btms-history]
-    if: always()
-    runs-on: ubuntu-latest
-    steps:
-      - name: checking
-        id: schedule_validation
-        run: echo "::set-output name=status::true"
-      - name: sleep 10 sec  
-        run: sleep 10 # 900 seconds = 15 minutes
-      - name: Job4 Testing
-        run: echo "Job4 Third" 
-      - name: Intentionally fail Job 4
-        run: exit 1    
+  # dev-imaging:
+  #   needs: [dev-btms, dev-btms-history]
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: checking
+  #       id: schedule_validation
+  #       run: echo "::set-output name=status::true"
+  #     - name: sleep 10 sec  
+  #       run: sleep 10 # 900 seconds = 15 minutes
+  #     - name: Job4 Testing
+  #       run: echo "Job4 Third" 
+  #     - name: Intentionally fail Job 4
+  #       run: exit 1    
         
         
   # qc-btms:
