Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,10 +46,10 @@ jobs:
     if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
     runs-on: ubuntu-latest
     steps:
-      # - name: Job2 Testing
-      #   run: echo "Job2 Second"
-      - name: Intentionally fail Job 2
-        run: exit 1
+      - name: Job2 Testing
+        run: echo "Job2 Second"
+      # - name: Intentionally fail Job 2
+      #   run: exit 1
     outputs:
       job_status: ${{ job.status }}
 
@@ -82,7 +82,7 @@ jobs:
     # if: ${{ needs.Schedule_Validation.outputs.status }}== 'true' && always ()
     runs-on: ubuntu-latest
     needs: [dev-btms, dev-btms-history,Schedule_Validation ]
-    if: ${{ needs.Schedule_Validation.outputs.status }}== 'true' &&  always () # always run even if a previous step fails
+    if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'  # always run even if a previous step fails
     steps:
       - name: Delay for 30 sec
         run: sleep 10 # 900 seconds = 15 minutes
