Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,8 +13,8 @@ jobs:
         run: exit 1
       - name: Job1 Testing
         run: echo "Job1 first"
-      - name: Intentionally fail Job 2
-        run: exit 1        
+      # - name: Intentionally fail Job 2
+      #   run: exit 1        
       - name: Run Steps in Parallel
         run: |
           sleep 10
