Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,8 +9,8 @@ jobs:
   New:
     runs-on: ubuntu-latest
     steps:
-      - name: Intentionally fail Job 2
-        run: exit 1
+      # - name: Intentionally fail Job 2
+      #   run: exit 1
       - name: Job1 Testing
         run: echo "Job1 first"
       # - name: Intentionally fail Job 2
