Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,10 +46,10 @@ jobs:
     if: ${{ needs.Schedule_Validation.outputs.status }}== 'true'
     runs-on: ubuntu-latest
     steps:
-      # - name: Job2 Testing
-      #   run: echo "Job2 Second"
-      - name: Intentionally fail Job 2
-        run: exit 1
+      - name: Job2 Testing
+        run: echo "Job2 Second"
+      # - name: Intentionally fail Job 2
+      #   run: exit 1
     outputs:
       job_status: ${{ job.status }}
 
@@ -57,10 +57,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: [dev-btms, dev-btms-history]
     if: needs.dev-btms.outputs.job_status != 'skipped' || needs.dev-btms-history.outputs.job_status != 'skipped'
-    # if: needs.dev-btms.outputs.job_status != 'skipped' && needs.dev-btms-history.outputs.job_status != 'skipped'
-    # /if: needs.dev-btms.outputs.job_status == 'running' && needs.dev-btms-history.outputs.job_status == 'running'
-    # if: always() || needs.dev-btms.result == 'skipped' || needs.dev-btms-history.result == 'skipped'
-    # if: needs.dev-btms.outputs.job_status == 'skipped' && needs.dev-btms-history.outputs.job_status == 'skipped'
     steps:
       - name: Delay for 30 sec
         run: sleep 30
